apiVersion: v1
kind: Deployment
metadata:
  name: django-app-deploy
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-application
  template: 
    metadata: 
      labels:
        app: django-application
    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim: 
            claimName: staticfiles-pvc
      containers:
        image: ivicazuz/django-kubernetes:1.0
        imagePolicy: Always
        name: django-app-container
        envFrom:
          - configMapRef:
              name: app-cm
        ports:
          - containerPort: 8000
        volumeMounts:
          - mountPath: "/data/static"
            name: staticfiles

