apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: django-app
spec:
  storageClassName: manual
  accesModes:
    - ReadWriteOnce
  resources:
    request:
      storage: 1Gi
  volumeName: postgres-pv